config/routes.rb
Rails.application.routes.draw do
  get 'inquiries/new'
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }
  
  get "/admin/top" => "users#top"

  devise_scope :admins do
    get '/admins/sign_in', to: 'admins/sessions#new'
    get '/admins/sign_out', to: 'admins/sessions#destroy'
  end
  
  get 'customers/show'
  devise_for :customers
  root to: 'homes#top'
  
  resources :items, only: [:new, :create, :index,:edit,:show,:update,:destroy]do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :customers, only: [:show,:edit,:update]
  
  
  get 'inquiries/new', as: 'inquiry'
  post 'inquiries' => 'inquiries#create'
  
  get 'thanks'=> 'inquiries#thanks', as: 'thanks'
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :profile_image
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  
   belongs_to :customer
   has_many :comments, dependent: :destroy
   attachment :image
   has_many :favorites, dependent: :destroy
   
  validates :name, presence: true
  validates :image, presence: true

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authenticate_customer!,except: [:top]
    before_action :configure_permitted_parameters, if: :devise_controller?


    def after_sign_in_path_for(resource)
      case resource
      when Admin
      admin_top_path
      when Customer
      items_path
      end
    end

	  def after_sign_up_path_for(resource)
      case resource
      when Admin
      admin_top_path
      when Customer
      root_path
      end
    end


     def after_sign_out_path_for(resource)
      if resource == :admin
      new_admin_session_path
      else
      new_customer_session_path
      end
    end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    item = Item.find(params[:item_id])
    comment = current_customer.comments.new(post_comment_params)
    comment.item_id = item.id
    comment.save
    redirect_to item_path(item)
  end

  def destroy
    Comment.find_by(id: params[:id]).destroy
    redirect_to item_path(params[:item_id])
  end
  
private

  def post_comment_params
    params.require(:comment).permit(:comment)
  end
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :authenticate_customer!


  def show
    @customer = Customer.find(params[:id])
    @items = @customer.items.page(params[:page]).per(3)
  end

  def edit
    @customer = Customer.find(params[:id])
    if @customer == current_customer
      render "edit"
    else
      redirect_to customer_path(current_customer.id)
    end
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customer_path(@customer.id)
  end

  def ensure_correct_user
   @customer = Customer.find(params[:id])
    unless @customer == current_customer
    redirect_to items_path
    end
  end


private

  def customer_params
    params.require(:customer).permit(:name, :profile_image,:introduction)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    item = Item.find(params[:item_id])
    favorite = current_customer.favorites.new(item_id: item.id)
    favorite.save
    redirect_to items_path
  end

  def destroy
    item = Item.find(params[:item_id])
    favorite = current_customer.favorites.find_by(item_id: item.id)
    favorite.destroy
    redirect_to items_path
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      redirect_to thanks_path
    else
      render :new
    end
  end

  def thanks
  end


private

  def inquiry_params
    params.require(:inquiry).permit(:title, :body)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_customer!
  before_action :ensure_correct_user,only: [:edit,:update,:destory]

  def new
     @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.customer_id = current_customer.id

    if @item.save
      redirect_to items_path
    else
      render :new
    end

  end

  def index
    @items = Item.page(params[:page]).reverse_order
    @customers = Customer.all
    @search = Item.ransack(params[:q])
    @products = @search.result(distinct: true)

  end

  def show
    @item = Item.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to item_path(item.id)
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to items_path
  end

  def ensure_correct_user
    @item = Item.find(params[:id])
    unless @item.customer_id == current_customer.id
      redirect_to items_path
    end
  end



private

  def item_params
    params.require(:item).permit(:name, :image, :caption)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!

  def top
    @inquiries = Inquiry.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center"><h2>プロフィール編集</h2>
      <%= form_with model:@customer, local:true do |f| %>
      
      <p class= "inputName"><label for="inputName">Name</label></p>
      <div class="field">
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
      </div>
      
      <p class= "inputImage"><label for="inputImage">ProfileImage</label></p>
      <div class="profile_image">
        <%= attachment_image_tag @customer, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
      </div>
      
      <div class="field">
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>
      
      <p class= "inputIntroduction"><label for="inputIntroduction">自己紹介</label></p>
      <div class="field">
        <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介"%>
      </div>
  
      <div class="profile_submit"><%= f.submit "変更を保存" %></div>
      <% end %>

    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 mt-4 text-center">
      <div class="card " style="width: 18rem;">
        <%= attachment_image_tag @customer, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <div class="card-body">
          <h5 class="card-title"><%= @customer.name %></h5>
          <p class="card-text"><%= @customer.introduction %></p>
        </div>
          <div class="card-body">
            <% if @customer == current_customer %>
            <p><%= link_to "プロフィール編集", edit_customer_path(@customer), class: "btn btn-secondary" %></p>
            <% end %>
          </div>
      </div>
    </div>

    <div class="col-lg-8 mt-4 text-center">
      <h2 class="post-index">投稿一覧</h2>
       <% @items.each do |item| %>
          <%= link_to item_path(item.id) do %>
            <%= attachment_image_tag item, :image, :fill, 60, 60%>
          <% end %>
       <p><%= item.name %></p>
       <% if item.customer == current_customer %>
       <p>
         <%= link_to '編集', edit_item_path(item.id), class: "btn btn-secondary" %>
         <%= link_to "削除", "/items/#{item.id}", method: :delete, class: "btn btn-danger" %>
       </p>
         <% end %>
       <% end %>
       <div class="paginate-show">
          <%= paginate @items %>
       </div>
   </div>
  </div>

app/views/inquiries/new.html.erb
<% if @inquiry.errors.any? %>
  <%= @inquiry.errors.count %>件のエラーが発生しました
  <% @inquiry.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<div class="container">
  <div class="row">
    <div class="col-md-7 text-center">
<h1>お問い合わせフォーム</h1>

  <%= form_with model: @inquiry, url:'/inquiries', local:true do |f| %>
    <div class="form-group">
      <label>件名</label>
      　　<%= f.text_field :title,class:"form-control"%>
    </div>


    <div class="form-group">
       <label>お問い合わせ内容</label>
      　　<%= f.text_area :body , class:"form-control" %>
    </div>

    <div>
       　<%= f.submit '送信' %>
    </div>

<% end %>

</div>
<div class="col-md-5 text-center">
  <a href="https://px.a8.net/svt/ejp?a8mat=3HKY8E+66O50Y+29Y0+1BNYOX" rel="nofollow">
  <img border="0" width="300" height="250" alt="" src="https://www22.a8.net/svt/bgt?aid=210929486374&wid=001&eno=01&mid=s00000010620008006000&mc=1"></a>
  <img border="0" width="1" height="1" src="https://www13.a8.net/0.gif?a8mat=3HKY8E+66O50Y+29Y0+1BNYOX" alt="">
</div>


</div>
</div>

app/views/inquiries/thanks.html.erb
<div class="container">  <!-- この行を追加 -->
   <div class="row">
      <div class="col-lg-12 text-center" >
        <h2>お問い合わせありがとうございます</h2>
        <p>ご記入していただいた情報は無事に送信されました。</p>
        <span><%= link_to "トップページに戻る", root_path, class:"btn btn-success" %></span>
     </div>
   </div>
</div>

app/views/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center"><h2>投稿編集</h2>
      <%= form_with model:@item, url:"/items/#{@item.id}", local:true do |f| %>
      
        <div class="field">
          <%= attachment_image_tag @item, :image, :fill, 200, 200, fallback: "no_image.jpg"%>
        </div>
        <div class="field">
      　　　<%= f.attachment_field :image, placeholder: "商品画像" %>
        </div>
        <div class="field">
          <h4>商品名</h4>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <h4>商品紹介</h4>
          <%= f.text_area :caption %>
        </div>
      <%= f.submit '保存' %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="search">
<%= search_form_for @search do |f| %>
  <%= f.search_field :caption_cont, placeholder: "キーワードを入力", required: true %>
  <%= f.submit "検索" %>
<% end %>
</div>


<div class="list-wrap">
<% if @search.conditions.present? %>
  <% @products.each do |product| %>
    <div class="list-box">
      <%= link_to item_path(product.id) do %>
        <%= attachment_image_tag product, :image, :fill, 200, 200, format: 'jpeg' %>
      <% end %>
    </div>
  <% end %>
<% end %>
</div>



<div class= "container">
  <div class = "row">
    <div class= "col-md-12 mt-5 text-center">
      <a href="https://px.a8.net/svt/ejp?a8mat=3HKY8E+7GIILU+4KMO+5Z6WX" rel="nofollow">
       <img border="0" width="468" height="60" alt="" src="https://www24.a8.net/svt/bgt?aid=210929486451&wid=001&eno=01&mid=s00000021336001004000&mc=1"></a>
       <img border="0" width="1" height="1" src="https://www13.a8.net/0.gif?a8mat=3HKY8E+7GIILU+4KMO+5Z6WX" alt="">
    </div>
  </div>
</div>


<div class= "paginate">
  <%= paginate @items %>
</div>

<div class="list-wrap">
<% @items.each do |item| %>
  <div class="list-box">
    <%= link_to item_path(item.id) do %>
      <%= attachment_image_tag item, :image, :fill, 200, 200, format: 'jpeg' %>
    <% end %>
  </div>
<% end %>
</div>

<div class= "paginate">
  <%= paginate @items %>
</div>

</div>

app/views/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 text-center">
        <h1>商品投稿</h1>
          <% if @item.errors.any? %>
            <%= @item.errors.count %>件のエラーが発生しました
            <% @item.errors.full_messages.each do |message| %>
            <%= message %>
            <% end %>
          <% end %>

          <%= form_with model: @item, local:true do |f| %>

          <div class="form-group mt-5">
          <h4>商品画像</h4>
            <%= f.attachment_field :image%>
          </div>

          <div class="form-group">
          <h4>商品名</h4>
            <%= f.text_field :name ,class:"form-control"%>
          </div>

          <div class="form-group">
          <h4>商品説明</h4>
            <%= f.text_area :caption,class:"form-control" %>
          </div>

          <%= f.submit '投稿' %>
          <% end %>

      </div>
              <div class="col-md-4 text-center">
          <a href="https://px.a8.net/svt/ejp?a8mat=3HKY8E+4FK6WI+29Y0+1HN5LT" rel="nofollow">
　　　　　<img border="0" width="300" height="250" alt="" src="https://www29.a8.net/svt/bgt?aid=210929486268&wid=001&eno=01&mid=s00000010620009010000&mc=1"></a>
　　　　　<img border="0" width="1" height="1" src="https://www14.a8.net/0.gif?a8mat=3HKY8E+4FK6WI+29Y0+1HN5LT" alt="">
        </div>
   </div>
</div>

app/views/items/show.html.erb
<div class="card-list-container py-5">
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <div class="card-body">
      <%= attachment_image_tag @item, :image,class:"card-img-top" %>
      <div class="row">
        <div class="col-2">
          <%= attachment_image_tag @item.customer, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            商品名：<%= @item.name %>
          </p>
          <p class="card-text">
            商品説明：<%= @item.caption %>
          </p>
          <p>
            <i class="fas fa-user"></i>　<%= @item.customer.name %>
          </p>

          <p>
            投稿日時：<%= @item.created_at.strftime('%Y/%m/%d') %>
          </p>
            <% if @item.customer == current_customer %>
              <%= link_to "削除", item_path(@item), class: "btn btn-danger", method: :delete %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
    <div class="card w-50 mx-auto mt-4 shadow-lg">
      <div class="row">
        <div class="col-md-12 text-center">
          <div class="card">
            <h5 class="card-header">コメント一覧 (コメント件数：<%= @item.comments.count %>)</h5>
              <div class="card-body">
                 <div class="comment-new">
                   <%= form_with(model:[@item, @comment], local: true) do |f| %>
                   <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
                   <p>
                     <%= f.submit "送信する" %>
                   </p>
                   <% end %>
                 </div>

               <% @item.comments.each do |comment| %>
                  <p><%= comment.created_at.strftime('%Y/%m/%d') %></p>
                  <p><%= attachment_image_tag comment.customer, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                  <%= comment.customer.name %></p>
                  <%= comment.comment %>
                  <% if comment.customer == current_customer %>
                    <%= link_to "削除", item_comment_path(comment.item, comment),class: "btn btn-danger", method: :delete %>
                  <% end %>
               <% end %>
             </div>
          </div>
       </div>
     </div>
   </div>
</div>