config/routes.rb
Rails.application.routes.draw do
  get 'inquiries/new'
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }
  
  get "/admin/top" => "users#top"

  devise_scope :admins do
    get '/admins/sign_in', to: 'admins/sessions#new'
    get '/admins/sign_out', to: 'admins/sessions#destroy'
  end
  
  get 'customers/show'
  devise_for :customers
  root to: 'homes#top'
  
  resources :items, only: [:new, :create, :index,:edit,:show,:update,:destroy]do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :customers, only: [:show,:edit,:update]
  
  
  get 'inquiries/new', as: 'inquiry'
  post 'inquiries' => 'inquiries#create'
  
  get 'thanks'=> 'inquiries#thanks', as: 'thanks'
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :profile_image
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  
   belongs_to :customer
   has_many :comments, dependent: :destroy
   attachment :image
   has_many :favorites, dependent: :destroy
   
  validates :name, presence: true
  validates :image, presence: true

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    item = Item.find(params[:item_id])
    comment = current_customer.comments.new(post_comment_params)
    comment.item_id = item.id
    comment.save
    redirect_to item_path(item)
  end

  def destroy
    Comment.find_by(id: params[:id]).destroy
    redirect_to item_path(params[:item_id])
  end
  
private

  def post_comment_params
    params.require(:comment).permit(:comment)
  end
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :authenticate_customer!


  def show
    @customer = Customer.find(params[:id])
    @items = @customer.items.page(params[:page]).per(3)
  end

  def edit
    @customer = Customer.find(params[:id])
    if @customer == current_customer
      render "edit"
    else
      redirect_to customer_path(current_customer.id)
    end
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customer_path(@customer.id)
  end

  def ensure_correct_user
   @customer = Customer.find(params[:id])
    unless @customer == current_customer
    redirect_to items_path
    end
  end


private

  def customer_params
    params.require(:customer).permit(:name, :profile_image,:introduction)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_customer!
  before_action :ensure_correct_user,only: [:edit,:update,:destory]

  def new
     @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.customer_id = current_customer.id

    if @item.save
      redirect_to items_path
    else
      render :new
    end

  end

  def index
    @items = Item.page(params[:page]).reverse_order
    @customers = Customer.all
    @search = Item.ransack(params[:q])
    @products = @search.result(distinct: true)

  end

  def show
    @item = Item.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to item_path(item.id)
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to items_path
  end

  def ensure_correct_user
    @item = Item.find(params[:id])
    unless @item.customer_id == current_customer.id
      redirect_to items_path
    end
  end



private

  def item_params
    params.require(:item).permit(:name, :image, :caption)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!

  def top
    @inquiries = Inquiry.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookingram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif+JP|Open+Sans&display=swap" rel="stylesheet">

  </head>

<body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><h2 class = "logo">Cookingram</h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li class="nav-item">
                 <%= link_to '投稿', new_item_path, class:"btn btn-secondary" %>
              </li>
              <li class="nav-item">
                 <%= link_to 'マイページ', customer_path(current_customer.id),class:"btn btn-secondary"  %>
              </li>
              <li class="nav-item">
                 <%= link_to '商品一覧', items_path,class:"btn btn-secondary"  %>
              </li>
              <li class="nav-item">
                 <%= link_to 'お問い合わせ', inquiry_path,class:"btn btn-secondary"  %>
              </li>
              <li class="nav-item">
                 <%= link_to "ログアウト", destroy_customer_session_path, class:"btn btn-danger" , method: :delete %>
              </li>
            <% elsif admin_signed_in?%>
              <li><%= link_to ' ログアウト', destroy_admin_session_path,class:"btn btn-danger", method: :delete %>
              </li>
            <% else %>
              <li class="nav-item">
                 <%= link_to "新規登録", new_customer_registration_path,class:"btn btn-secondary" %>
              </li>
              <li class="nav-item">
                 <%= link_to "ログイン", new_customer_session_path,class:"btn btn-secondary" %>
              </li>
            <% end %>
             </ul>
          </div>
        </div>
      </nav>
  </header>
  <%= yield %>
</body>
</html>